<?php
defined( 'ABSPATH' ) || exit;

/*******************************************************************************
 * Module: CDN Images — URL rewrite extension point                            *
 *                                                                             *
 * Provides a `reloaded_image_url` filter applied to ALL image URLs            *
 * generated by WordPress (uploads). Lets you rewrite to a CDN host            *
 * (Cloudflare Images, Bunny, KeyCDN, etc.) without editing theme core.        *
 *                                                                             *
 * State: DORMANT by default. With no filter callbacks, URLs pass intact.      *
 *                                                                             *
 * To enable (e.g. child theme, mu-plugin, or a wp-config-loaded snippet):     *
 *                                                                             *
 *   add_filter( 'reloaded_image_url', function( $url, $context ) {            *
 *       return str_replace(                                                   *
 *           'https://reloaded.com.br/wp-content/uploads',                     *
 *           'https://reloaded.b-cdn.net',                                     *
 *           $url                                                              *
 *       );                                                                    *
 *   }, 10, 2 );                                                               *
 *                                                                             *
 * Coverage — points where the filter is applied:                              *
 *   1. wp_get_attachment_url           → canonical attachment URL             *
 *   2. wp_get_attachment_image_src     → <img> src with resolved size         *
 *   3. wp_calculate_image_srcset       → each URL of the responsive srcset    *
 *                                                                             *
 * Doesn't cover (intentional):                                                *
 *   - External URLs (non-uploads) — pass through transparently                *
 *   - Hardcoded URLs in templates — if any, refactor to use WP helpers        *
 *                                                                             *
 * Works with mod-image-formats: the filter gets URLs ALREADY resolved (avif/  *
 * webp if applicable), so the CDN serves whatever format is on disk.          *
 ******************************************************************************/

/**
 * Internal helper — applies the `reloaded_image_url` filter to a URL.
 *
 * Only acts on URLs inside wp_upload_dir (ignores Gravatar avatars, external
 * images, etc.). Silent no-op if the URL isn't from uploads.
 *
 * @param string $url     URL to possibly rewrite.
 * @param string $context Hint for the callback: 'attachment_url', 'image_src',
 *                        'srcset'. Allows different strategies per context.
 * @return string Rewritten URL (or original if no callback is hooked).
 */
function rd_cdn_maybe_rewrite( string $url, string $context = '' ): string {
	if ( '' === $url ) {
		return $url;
	}

	// Only rewrite URLs from our own uploads. External ones (Gravatar, oEmbed, etc.)
	// pass through intact — otherwise the CDN would serve a 404.
	$upload_dir = wp_upload_dir();
	$base_url   = isset( $upload_dir['baseurl'] ) ? (string) $upload_dir['baseurl'] : '';
	if ( '' === $base_url || strpos( $url, $base_url ) !== 0 ) {
		return $url;
	}

	/**
	 * Rewrites an image URL before serving.
	 *
	 * @param string $url     Absolute URL inside wp-content/uploads.
	 * @param string $context 'attachment_url' | 'image_src' | 'srcset'.
	 */
	return (string) apply_filters( 'reloaded_image_url', $url, $context );
}

/**
 * Filter on wp_get_attachment_url — canonical attachment URL (no size).
 */
function rd_cdn_filter_attachment_url( $url ) {
	return rd_cdn_maybe_rewrite( (string) $url, 'attachment_url' );
}
add_filter( 'wp_get_attachment_url', 'rd_cdn_filter_attachment_url', 99 );

/**
 * Filter on wp_get_attachment_image_src — array [url, width, height, is_intermediate].
 * URL is index 0; we rewrite only it.
 */
function rd_cdn_filter_image_src( $image ) {
	if ( ! is_array( $image ) || empty( $image[0] ) ) {
		return $image;
	}
	$image[0] = rd_cdn_maybe_rewrite( (string) $image[0], 'image_src' );
	return $image;
}
add_filter( 'wp_get_attachment_image_src', 'rd_cdn_filter_image_src', 99 );

/**
 * Filter on wp_calculate_image_srcset — rewrites each URL of the responsive srcset.
 *
 * Structure received: [ width => [ 'url' => '...', 'descriptor' => 'w', 'value' => N ] ]
 */
function rd_cdn_filter_srcset( $sources ) {
	if ( ! is_array( $sources ) ) {
		return $sources;
	}
	foreach ( $sources as $width => $source ) {
		if ( ! empty( $source['url'] ) ) {
			$sources[ $width ]['url'] = rd_cdn_maybe_rewrite( (string) $source['url'], 'srcset' );
		}
	}
	return $sources;
}
add_filter( 'wp_calculate_image_srcset', 'rd_cdn_filter_srcset', 99 );
