<?php
defined( 'ABSPATH' ) || exit;

/********************************************************************************
 * Module: Critical CSS injection + async stylesheet loading                    *
 *                                                                              *
 * Implements the "Critical CSS inline + defer" pattern Lighthouse recommends   *
 * to eliminate render-blocking of the main `<link rel="stylesheet">`.          *
 *                                                                              *
 * Flow (when enabled via toggle):                                              *
 *   1. wp_head priority 0 → injects `<style id="rd-critical-css">…</style>`    *
 *      containing the prebuilt critical CSS for this template (5-20 KB inline).*
 *   2. style_loader_tag filter → turns the `<link rel="stylesheet">` of the    *
 *      `rd-main-style` handle into `<link rel="preload" as="style"             *
 *      onload="this.rel='stylesheet'">`, loading asynchronously.               *
 *   3. <noscript> fallback → ensures browsers without JS still fetch           *
 *      the CSS synchronously (accessibility + Lynx/curl/etc).                  *
 *                                                                              *
 * Critical CSS built offline via `npm run critical:{template}` (Node script    *
 * `tools/critical/extract.js` using the `critical` package + Puppeteer).       *
 * Files: `assets/css/critical-{template}.css` — pre-versioned in the repo.     *
 *                                                                              *
 * Supported templates:                                                         *
 *   - home (is_home() || is_front_page())                                      *
 *   - single (is_single() && get_post_type() === 'post')                       *
 *   - page (is_page())                                                         *
 *   - archive (is_archive() || is_home() with custom posts_per_page)           *
 *   - search (is_search())                                                     *
 *   - fallback: home                                                           *
 *                                                                              *
 * Toggle: Panel → Performance → "Inline Critical CSS" (default OFF, opt-in).   *
 *                                                                              *
 * FOUC risk: if you forget to regenerate the critical after a big              *
 * above-the-fold SCSS change, a brief visual flash appears when the full       *
 * CSS finishes loading. Doesn't break functionality — just looks ugly.         *
 *******************************************************************************/

/**
 * Detects the current template and returns the corresponding critical CSS key.
 *
 * @return string Template key ('home', 'single', 'page', 'archive', 'search').
 */
function rd_critical_css_template_key() {
	if ( is_singular( 'post' ) ) {
		return 'single';
	}
	if ( is_page() ) {
		return 'page';
	}
	if ( is_search() ) {
		return 'search';
	}
	if ( is_archive() || is_category() || is_tag() || is_author() || is_date() || is_tax() ) {
		return 'archive';
	}
	// is_home() / is_front_page() / any other context falls back to home.
	return 'home';
}

/**
 * Reads the current template's critical CSS file and returns its content.
 * Returns an empty string if the file doesn't exist (degrades to normal loading).
 *
 * @return string Critical CSS ready for inline injection (already minified).
 */
function rd_critical_css_get_content() {
	$template = rd_critical_css_template_key();
	$path     = get_template_directory() . '/assets/css/critical-' . $template . '.css';

	if ( ! file_exists( $path ) ) {
		// Fallback: try home if the specific template doesn't exist.
		$path = get_template_directory() . '/assets/css/critical-home.css';
		if ( ! file_exists( $path ) ) {
			return '';
		}
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- path controlled by get_template_directory(), local theme file.
	$content = file_get_contents( $path );

	return false !== $content ? (string) $content : '';
}

/**
 * Injects the critical CSS inline in <head> at priority 0 (before everything,
 * including the font preload at priority 1). Ensures above-the-fold rules
 * are available as soon as the browser parses the head.
 */
function rd_critical_css_inject_inline() {
	if ( ! rd_get_option_bool( 'inline_critical_css' ) ) {
		return;
	}
	if ( is_admin() ) {
		return;
	}

	$content = rd_critical_css_get_content();
	if ( '' === $content ) {
		return;
	}

	$nonce_attr = rd_csp_nonce_attr();
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS content pre-generated by the trusted extractor (`critical` npm package). HTML-escaping would break valid CSS. Nonce attribute already escaped by rd_csp_nonce_attr().
	echo "\n<style id=\"rd-critical-css\"" . $nonce_attr . '>' . $content . "</style>\n";
}
add_action( 'wp_head', 'rd_critical_css_inject_inline', 0 );

/**
 * Turns the `rd-main-style` handle's `<link rel="stylesheet">` into
 * async preload with a noscript fallback. Only acts when the toggle is ON.
 *
 * Pattern recommended by web.dev:
 *   <link rel="preload" href="..." as="style" onload="this.rel='stylesheet'">
 *   <noscript><link rel="stylesheet" href="..."></noscript>
 *
 * @param string $tag    The full HTML of the <link> tag.
 * @param string $handle The enqueue handle (registered in `mod-performance.php`).
 * @return string The modified tag (or unchanged if handle != rd-main-style).
 */
function rd_critical_css_defer_main_stylesheet( $tag, $handle ) {
	if ( ! rd_get_option_bool( 'inline_critical_css' ) ) {
		return $tag;
	}
	if ( is_admin() ) {
		return $tag;
	}
	if ( 'rd-main-style' !== $handle ) {
		return $tag;
	}
	// If the critical CSS is missing (template without a generated file), don't
	// defer — keep it synchronous to avoid a CSS-less screen.
	if ( '' === rd_critical_css_get_content() ) {
		return $tag;
	}

	// Extract the href from the original tag via a simple regex (href="..." attribute).
	if ( ! preg_match( '/href=([\'"])([^\'"]+)\1/', $tag, $matches ) ) {
		return $tag;
	}
	$href = $matches[2];

	// Rebuild as preload + swap script + noscript fallback.
	//
	// We used to use inline `onload="this.rel='stylesheet'"` on the <link>, but
	// inline event handlers ('unsafe-hashes' in CSP) aren't covered by
	// nonce/strict-dynamic. Refactored to a <script nonce> that adds the
	// listener via JS — same behavior, without an inline handler.
	//
	// The script is placed immediately after the <link>, so the chance of the
	// load firing before the listener registers is minimal. The `l.sheet` check
	// covers the HTTP cache case (browser cached the CSS and populated sheet before
	// the script ran).
	$nonce_attr = rd_csp_nonce_attr();
	// phpcs:disable WordPress.WP.EnqueuedResources.NonEnqueuedStylesheet -- replacing, via the style_loader_tag filter, the link already enqueued by mod-performance.php; this is the official web.dev pattern for critical-CSS deferred loading.
	$preload     = sprintf(
		'<link rel="preload" href="%s" as="style" data-rd-defer-css>',
		esc_url( $href )
	);
	$swap_script = '<script' . $nonce_attr . '>(function(){var l=document.querySelector(\'link[data-rd-defer-css]\');if(!l)return;var done=false;var swap=function(){if(done)return;done=true;l.rel=\'stylesheet\';l.removeAttribute(\'data-rd-defer-css\');};l.addEventListener(\'load\',swap);if(l.sheet)swap();})();</script>';
	$noscript    = sprintf(
		'<noscript><link rel="stylesheet" href="%s"></noscript>',
		esc_url( $href )
	);
	// phpcs:enable WordPress.WP.EnqueuedResources.NonEnqueuedStylesheet

	return $preload . "\n" . $swap_script . "\n" . $noscript . "\n";
}
add_filter( 'style_loader_tag', 'rd_critical_css_defer_main_stylesheet', 10, 2 );
